### ISSUE TITLE
Question about rust version requirements

### ISSUE THREAD

**Issue by vmiheer** [s3bk/bullet#3]
hi is rust nightly is mandatory to use this crate?
I see error:
```
   Compiling math_traits v0.1.6
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/mvaidya/.cargo/registry/src/github.com-1ecc6299db9ec823/math_traits-0.1.6/src/lib.rs:1:1
  |
1 | #![feature(core_intrinsics)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/mvaidya/.cargo/registry/src/github.com-1ecc6299db9ec823/math_traits-0.1.6/src/lib.rs:2:1
  |
2 | #![feature(const_fn)]
  | ^^^^^^^^^^^^^^^^^^^^^
```

I am also not sure where is `math/.cargo/config` the README is referring to.

**Comment by s3bk** [comment]
@vmiheer Yes, most of my code is bleeding edge.

Nightly is definitely needed and it may not compile at all sometimes.

**Comment by vmiheer** [comment]
> I am also not sure where is math/.cargo/config the README is referring to.
Can you help with above line in readme?
